### ISSUE TITLE
Reason behind not using the interrupt functionality?

### ISSUE THREAD

**Issue by barafael** [kriswiner/MPU6050#21]
Your sketches have proven very useful and you clearly know what you are doing. I ordered an 'Ultimate IMU' from tindie.
What is the reason you do not use the interrupt pin? I2Cdevlib uses it, and your sketch mentions it as well.

**Comment by kriswiner** [comment]
We do use the interrupt pin and I would recommend it, we didn;t always when
I wrote those earlier sketches.
