### ISSUE TITLE
convert it a library

### ISSUE THREAD

**Issue by habi3000** [kriswiner/MPU6050#26]
hi, 
is it possible to convert the functions and the code to an arduino library so it becomes easier to use, by #including it to our file with out having to add the whole code to our file?
ps. i am willing to help if it is possible

**Comment by kriswiner** [comment]
Yes, it is straightforward to do this.

**Comment by habi3000** [comment]
thanks for your response 
i tried to do it but got lots of errors. could you please guide me?

**Comment by kriswiner** [comment]
Use this as a guide:

https://github.com/kriswiner/MPU9250/tree/master/MPU9250_BME280_SPIFlash_Ladybug

**Comment by habi3000** [comment]
thanks a lot, it worked and fixed my problem
thanks again for your response and time.
