### ISSUE TITLE
seek help：how can i get the angle without using Arduino

### ISSUE THREAD

**Issue by Tednsn** [kriswiner/MPU6050#34]
Hello , sir . in your demonstration，we can get information from mpu6050 by using arduino,but if  i want get   information by mpu6050 and usb-i2c transverter instead of arduino ，what should a freshman do .Can you give me a train of thought，Thanks a million！

**Comment by kriswiner** [comment]
Maybe you can use the DMP, but generally you need some device to issue I2C
commands. What would it be in this case, the pc or linux box?

**Comment by mengjiehehe** [comment]
Thans for your reply, i want to use the dates of mpu6050 in pc of  linux  system and i get the information by CUTECOM. But so far i have not found a driver that I can use directly. Maybe I should learn more about it ,and then write my own driver for it .and your demo is good example for me,thanks a lot .

**Comment by kriswiner** [comment]
Better is to use an MCU to collect the data from the MPU6050, and send the
data to the pc via USB serial.

**Comment by Tednsn** [comment]
Thanks a lot.
