### ISSUE TITLE
How to produce the Mxy Mxz Myz point picture?

### ISSUE THREAD

**Issue by FN0005** [kriswiner/MPU6050#44]
Is it generated using matlab's plot3 or scatter3 code and then converted to 2D picture?
Can provide a reference code?Thanks!

![4EFA7B4B-A9A5-4C16-B6BA-899B60956816](https://user-images.githubusercontent.com/57161804/67822410-400f7180-fafb-11e9-9e61-7d80e27efe2d.jpeg)

**Comment by kriswiner** [comment]
Output Mx, My Mz on the serial monitor and use excel or equivalent to plot
one vs the other.

**Comment by FN0005** [comment]
Use excel scatter plot function？
Mxy is z vs xy?

**Comment by kriswiner** [comment]
Mx vs My, for example, any plot program will do, really not that hard....

**Comment by FN0005** [comment]
Ok,for example,the attached file is my magnetometer data but I don't know how to use the excel scatter plot function because we need to project the XY YZ XZ generation point onto the plane,so do you have any reference excel file for reference?Thanks!
[01.xlsx](https://github.com/kriswiner/MPU6050/files/3787218/01.xlsx)

**Comment by kriswiner** [comment]
I have no idea what you mean. I simply plot Mx vs My, Mx vs Mz, etc. Why do
you need to do more than this?

**Comment by FN0005** [comment]
I understand what you mean but how do you place the Mxz Mxz Mxz in the same plane?

**Comment by FN0005** [comment]
This is my question
![01](https://user-images.githubusercontent.com/57161804/67835241-6dbce080-fb24-11e9-889d-78fd538cc310.jpg)
